### ISSUE TITLE
Feature Request: Clear

### ISSUE THREAD

**Issue by markbloomfield** [logger-app/logger-app#37]
Small thing, but would be great if I could 'clear' a view :)

**Comment by rosscourt** [comment]
Hi, there is a "Clear output" button in the top right corner next to the "Start watching" button bit only when the log is inactive.

Are you suggesting this button is available while the log is active? No reason it shouldn't be I guess

**Comment by markbloomfield** [comment]
Ya I found that button yesterday night when I stopped logging after the days work... Would be useful if I could intermittently clear the view without having to stop+start...

**Comment by rosscourt** [comment]
This change has been made and released in v1.0.4.

Thanks.
